name: Upload Files to Repository
on:
  push:
    branches:
      - main  # تأكد من تغيير الفرع إلى الفرع الذي تستخدمه

jobs:
  upload_files:
    runs-on: ubuntu-latest
    steps:
      # الخطوة 1: Checkout المستودع
      - name: Checkout repository
        uses: actions/checkout@v2

      # الخطوة 2: إعداد Git
      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your_email@example.com"

      # الخطوة 3: إضافة أو تحديث الملفات
      - name: Add new files or update existing files
        run: |
          echo "This is a test file" > newfile.txt  # أضف أو قم بتعديل الملفات هنا

      # الخطوة 4: إضافة الملفات إلى Git
      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Add new files via GitHub Action" || echo "No changes to commit"

      # الخطوة 5: دفع التغييرات إلى GitHub
      - name: Push changes to GitHub
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
